### ISSUE TITLE
Retrospectives guide link does not resolve

### ISSUE THREAD

**Issue by garethaledavies** [josephearl/awesome-retrospectives#17]
Hey @josephearl. I noticed that the [retrospectives guide link](https://academy.retrium.com/ultimate-guide-to-agile-retrospectives/) on the resource does not resolve. I don't think it's just my machine (tried it on mobile and another laptop).

In case you're looking for a quick fix, I put a similar guide together [here](https://www.parabol.co/resources/how-to-run-an-online-sprint-retrospective/). 

<img width="1400" alt="Screenshot 2023-09-20 at 20 35 24" src="https://github.com/josephearl/awesome-retrospectives/assets/15236825/ea672dd0-9586-4b2f-a62f-3acf5fd813df">

**Comment by josephearl** [comment]
Thanks for reporting, should be fixed now - looks like it moved to https://www.retrium.com/ultimate-guide-to-agile-retrospectives/retrospectives-101

Feel free to submit a PR adding your guide as an additional link
